name: 'dbt_ml_preprocessing'
version: '1.0.0'

require-dbt-version: ">=0.15.1"

config-version: 2

profile: "integration_tests"

source-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]
macro-paths: ["macros"]
log-path: "logs"
